restaurant:
  name: French Restaurant
  capacity: 75
  description: "Name: ${restaurant.name}. Capacity: ${restaurant.capacity}."
  menu:
    itemsString: Spaghetti Bolognese,Caesar Salad,Grilled Salmon