restaurant.name=French Restaurant
restaurant.capacity=21
#restaurant.description=Name: ${restaurant.name}. Capacity: ${restaurant.capacity}.

restaurant.menu.itemsString=Spaghetti Bolognese,Caesar Salad,Grilled Salmon